language: node_js
node_js:
- '4.2.3'
sudo: true
# hack to allow building modern cpp bins, travis has old g++ compiler
# found https://github.com/laverdet/node-fibers/issues/249
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
# end hack
branches:
  only:
  - master
  - develop
services:
- mongodb
before_install:
- curl https://install.meteor.com/ | sh
install:
- npm install --development
script:
- echo Running tests and hinting
- npm run jshint
before_deploy:
- ./scripts/packageOfflineDatabase.js > app/public/offline.js
- cd app && meteor remove-platform ios android
- "if [ \"$TRAVIS_BRANCH\" == 'master' ]; then cp app/private/live-robots.txt app/public/robots.txt ; fi"
- "if [ \"$TRAVIS_BRANCH\" == 'master' ]; then npm run buildForLiveDeploy ; fi"
- "if [ \"$TRAVIS_BRANCH\" == 'develop' ]; then npm run buildForDevDeploy ; fi"
- rm -rf app
- rm -rf node_modules
- npm run buildProdDeps
- npm install --production
deploy:
  provider: heroku
  app:
    develop: inspire-me-dev
    master: inspire-me-live
  strategy: api
  skip_cleanup: true
  api_key:
    secure: xIgO26S07cyAzG+3EW6PCNT6pPMY2NFmBXEepvZkTdBmxiEppXg2ne4zUJiX8BBSh6Furp0v035pH9aCB7ppc2bjHzNXqe0kWpYGcjZh+V8CBzGvgJQO0/6RrcZgRd4HluSVRVvbAqzdSTeHXScExOsYR0/eEXR9cAq337WqkAWXLvYESKZbUn+THRVCqOV46e9jlea+dKa9oHT6pyC9hQXjk2ZmWaGMNaE3R09PGJnS8Nalk/mqha3x0LuBCPDdEtgKrLgEY2e/2ddm5QQ4Gn8NKXWKBUx6Z1Yey+k0+P89Qr5NpECnxwypN49PBxFqR+6EERlpHWOrpxkcpYWf8aAOrYF91jxEVWoNc2D1X288loVZbrrBMu8b/Cylv7Ho8XHjaPBoC97c9ehZSpPyIAYc70H1a+GOl6iYa9z8XIrCKA867z1HkxH7M2utBxpzV+48eMGwaredMh1esD66k/XLCsPQK5LjCkA0zJSALQF+JAsoqUTOaYH2gQuBaiOh8h05w9XLH+xkL076EybQeLtfqemp1iDm/X0Kn/EijofvMej7ox5WKPfwgfeuWaOfco3cJgHIrhZvtLXWOqEj5NAYfnIRJy535/6NrnpKtkt+k2M0MsVlrFPAZ1A4Bl8StV1xDKvQSWPqdgxsSd/9dhoHjVAr8xBUpubZf8fnkxM=
notifications:
  email:
    recipients:
    - rob@neontribe.co.uk
    on_sucess: change
    on_failure: change
