language: node_js
node_js:
- '0.10'
sudo: true
branches:
  only:
  - master
  - develop
services:
- mongodb
before_install:
- curl https://install.meteor.com/ | sh
install:
- npm install --development
script:
- echo Running tests and hinting
- npm run jshint
before_deploy:
- ./scripts/packageOfflineDatabase.js > app/client/offline.js
# we need to copy across the correct robots.txt before building
- if [ "$TRAVIS_BRANCH" == 'master' ]; then cp app/private/live-robots.txt app/public/robots.txt ; fi
- if [ "$TRAVIS_BRANCH" == 'master' ]; then npm run buildForLiveDeploy ; fi
- if [ "$TRAVIS_BRANCH" == 'develop' ]; then npm run buildForDevDeploy ; fi
- rm -rf app
- rm -rf node_modules
- npm run buildProdDeps
- npm install --production
deploy:
  provider: heroku
  app:
    develop: inspire-me-dev
    master: inspire-me-live
  strategy: api
  skip_cleanup: true
  api_key:
    secure: RBNskLVHmvviRQZd9qiDGfkSdwsq9/Q/+ns2z+ilXa0gcSnDcYUvx7Ynh/eZcSZm2NIpkz5C3MmdG8pTwOtyl25N+g5eqD0jlWsmwIE4TtQ+3bJk0paNxi8Uh3ulL6ddi6KQgtI5DLbJnkzT26WI+Oj2tT3U3B/5NtMsd+3gmkQ=
notifications:
  email:
    recipients:
    - rob@neontribe.co.uk
    on_sucess: change
    on_failure: change
